<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
	<LangVersion>latest</LangVersion>
	<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	<Configurations>Debug;Release;Patch;Major</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Compress\Compress.csproj" />
    <ProjectReference Include="..\RVIO\RVIO.csproj" />
  </ItemGroup>

</Project>
