<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Configurations>Debug;Release;Patch;Major</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\build\Debug\RVUnZip</OutputPath>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<OutputPath>..\build\Release\RVUnZip</OutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Major|AnyCPU'">
		<OutputPath>..\build\Release\RVUnZip</OutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Patch|AnyCPU'">
		<OutputPath>..\build\Release\RVUnZip</OutputPath>
	</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Compress\Compress.csproj" />
    <ProjectReference Include="..\RVIO\RVIO.csproj" />
  </ItemGroup>

</Project>
